1. Melakukan berbagai operasi yg diberikan dengan numpy

In [1]:
import numpy as np

In [2]:
# buat matrix X berukuran 2x3 menggunakan numpy
x = np.array([[1, 5, 18], [85, 55, 75]])
x

array([[ 1,  5, 18],
       [85, 55, 75]])

In [3]:
# tampilkan ukuran dari matrix X
x.shape

(2, 3)

In [4]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
x[:, 0]

array([ 1, 85])

In [5]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
x[1, :]

array([85, 55, 75])

2. Melakukan Operasi yg telah dilakukan menggunakan pytorch dan tensorflow

In [6]:
import torch
import tensorflow as tf

In [7]:
# buat matrix x_t berukuran 2x3 menggunakan pytorch
x_t = torch.tensor([[1, 57, 91], [51, 49, 55]])
x_t

tensor([[ 1, 57, 91],
        [51, 49, 55]])

In [8]:
# tampilkan ukuran dari matrix x_t
x_t.shape

torch.Size([2, 3])

In [10]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X_t
x_t[:, 0]

tensor([ 1, 51])

In [11]:
# tampilkan seluruh elemen dari baris kedua dari matrix X_t
x_t[1, :]

tensor([51, 49, 55])

In [14]:
# buat matrix x_t berukuran 2x3 menggunakan tensorflow
x_tf = tf.Variable([[1, 5, 27], [55, 95, 55]])
x_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 1,  5, 27],
       [55, 95, 55]], dtype=int32)>

In [15]:
# tampilkan ukuran dari matrix x_tf
x_tf.shape

TensorShape([2, 3])

In [16]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X_tf
x_tf[:, 0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 1, 55], dtype=int32)>

In [17]:
# tampilkan seluruh elemen dari baris kedua dari matrix X_tf
x_tf[1, :]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([55, 95, 55], dtype=int32)>