1.buat vector x dengan ukuran 3x1

In [2]:
import numpy as np

In [3]:
# buat vector x dengan ukuran 3x1
x = np.array([[10],
             [11],
             [58]])
x

array([[10],
       [11],
       [58]])

In [4]:
# hitung nilai L2 norm dari vector x
(10**2 + 11**2 + 58**2)**(1/2)

59.87486951969081

2. buat vector v dengan ukuran (3,4)

In [5]:
# buat vector v dengan elemen (3,4)
v = np.array([1, 70, 35])
v

array([ 1, 70, 35])

In [6]:
# hitung nilai L2 norm dari vector v
(1**2 + 70**2 + 35**2)**(1/2)

78.26876771739798

In [7]:
# tampilkan unit vector dari vector v
norm = np.linalg.norm(x) # buat ngitung panjang vector
x_unit = x / norm # buat ngitung unit vector
x_unit

array([[0.16701498],
       [0.18371648],
       [0.96868687]])

In [8]:
# hitung panjang unit vector dari vector v
np.linalg.norm(x_unit)

np.float64(1.0)