Melakukan operasi apapun yang ditentukan dengan numpy



In [3]:
import numpy as np

In [4]:
# buat vector x dengan ukuran 3x1
x = np.array([[1],
             [10],
             [31]])
x

array([[ 1],
       [10],
       [31]])

In [5]:
# hitung panjang vector x
len(x)

3

In [6]:
# tampilkan ukuran vector x
x.shape

(3, 1)

In [7]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [8]:
# akses elemen pertama dari vector x
x[0]

array([1])

In [9]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.ndarray

2. Vectors Transposition

In [10]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([[ 1, 10, 31]])

In [11]:
# tampilkan ukuran dari vector x_t
x_t.shape

(1, 3)

In [12]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[49,51,19]])
y

array([[49, 51, 19]])

In [13]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y_t = y.T
y_t

array([[49],
       [51],
       [19]])

In [14]:
# tampilkan ukuran dari vector x_t
x_t.shape

(1, 3)

3. lakukan soal nomor 2 menggunakan pytorch dan tensorflow

In [15]:
import torch
import tensorflow as tf

In [16]:
# lakukan transpose pada vector x dan simpan pada variabel x_pt
x_pt = torch.tensor([[91, 19, 17]])
x_pt = x_pt.T
x_pt

tensor([[91],
        [19],
        [17]])

In [17]:
# tampilkan ukuran dari vector x_pt
x_pt.shape

torch.Size([3, 1])

In [18]:
# lakukan transpose pada vector y dan simpan pada variabel y_pt
y_pt = torch.tensor([[58],[61],[5]])
y_pt = y_pt.T
y_pt

tensor([[58, 61,  5]])

In [19]:
# tampilkan ukuran dari vector x_pt
x_pt.shape

torch.Size([3, 1])

In [20]:
# lakukan transpose pada vector x dan simpan pada variabel x_tf
x_tf = tf.Variable([[51, 15, 11]])
x_tf = tf.transpose(x_tf)
x_tf

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[51],
       [15],
       [11]], dtype=int32)>

In [21]:
# tampilkan ukuran dari vector x_tf
x_tf.shape

TensorShape([3, 1])

In [22]:
# lakukan transpose pada vector y dan simpan pada variabel y_tf
y_tf = tf.Variable([[50],[71],[55]])
y_pt = tf.transpose(y_tf)
y_pt

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[50, 71, 55]], dtype=int32)>

In [23]:
# tampilkan ukuran dari vector x_tf
x_tf.shape

TensorShape([3, 1])