### 1. Lakukan perhitungan soal exercise menggunakan collab

In [1]:
import torch

1.

In [2]:
# A
A = torch.tensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
A

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [3]:
# B
B = torch.tensor([[-1], [1], [-2]])
B

tensor([[-1],
        [ 1],
        [-2]])

In [4]:
# AxB
torch.matmul(A, B)

tensor([[ -3],
        [ -9],
        [-15]])

2.

In [5]:
#
I = torch.tensor ([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
I

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [6]:
# IxB
torch.matmul(I, B)

tensor([[-1],
        [ 1],
        [-2]])

3.

In [7]:
# M_q
M_q = torch.tensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
M_q

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [8]:
# V_q
V_q = torch.tensor([[-1, 1, -2], [0, 1, 2]]).T
V_q

tensor([[-1,  0],
        [ 1,  1],
        [-2,  2]])

In [9]:
# M_qxV_q
torch.matmul(M_q, V_q)

tensor([[ -3,   5],
        [ -9,  14],
        [-15,  23]])