### 1. Buat matrix X ukuran 2x2, lalu diinverskan, dan hasil invers tersebut dikalikan dengan matrix X

In [2]:
import numpy as np
import matplotlib.pyplot as plt

1.1 buat matrikx X ukuran 2x2 menggunakan numpy

In [3]:
# matrix X ukuran 2x2
X = np.array([[1, 2], [-3, -4]])
X

array([[ 1,  2],
       [-3, -4]])

1.2 buat invers dari matrix X dan beri nama Xinv menggunakan numpy

In [4]:
# buat invers dari matrix X
Xinv = np.linalg.inv(X)
Xinv

array([[-2. , -1. ],
       [ 1.5,  0.5]])

1.3 kalikan X dan Xinv menggunakan numpy

In [5]:
# X dikali Xinv
np.dot(X, Xinv)

array([[ 1.0000000e+00,  0.0000000e+00],
       [-8.8817842e-16,  1.0000000e+00]])

Itu bukan salah, tapi efek pembulatan (floating point), Itu tetap benar, cuma error pembulatan komputer.

### 2. Selesaikan persamaan berikut menggunakan numpy, tensorflow, dan pytorch

Dari gambar, sistem persamaannya adalah:
*   4b  + 2c =4
*   −5b − 3c =−7



> Kita ubah ke bentuk matriks:
```
|4 ,  2|  |b| = | 4|
|-5, -3|  |c| = |-7|

In [6]:
# numpy
A = np.array([[4, 2],
              [-5, -3]])

B = np.array([4, -7])

solusi = np.linalg.solve(A, B)

b, c = solusi
print("b =", b)
print("c =", c)

b = -0.9999999999999986
c = 3.999999999999998


In [7]:
# tensorflow
import tensorflow as tf
A = tf.constant([[4.0, 2.0],
                 [-5.0, -3.0]])

B = tf.constant([[4.0],
                 [-7.0]])

solusi = tf.linalg.solve(A, B)

b = solusi[0][0].numpy()
c = solusi[1][0].numpy()

print("b =", b)
print("c =", c)

b = -0.99999946
c = 3.999999


In [9]:
# PyTorch
import torch
A = torch.tensor([[4.0, 2.0],
                  [-5.0, -3.0]])

B = torch.tensor([[4.0],
                  [-7.0]])

solusi = torch.linalg.solve(A, B)

b = solusi[0][0].item()
c = solusi[1][0].item()

print("b =", b)
print("c =", c)

b = -1.0
c = 4.0
