### 1. buat matrix A dengan ukuran 2x3 dan vector b berukuran 3x1

numpy

In [9]:
import numpy as np

In [10]:
A = np.array([[4, 5, 6], [7, 8, 9]])
A

array([[4, 5, 6],
       [7, 8, 9]])

In [14]:
b = np.array([[3], [1], [4]])
b

array([[3],
       [1],
       [4]])

pytorch

In [1]:
import torch

In [2]:
A_pt = torch.tensor([[4, 5, 6], [7, 8, 9]])
A_pt

tensor([[4, 5, 6],
        [7, 8, 9]])

In [15]:
b_pt = torch.tensor([[3], [1], [4]])
b_pt

tensor([[3],
        [1],
        [4]])

tensorflow

In [5]:
import tensorflow as tf

In [6]:
A_tf = tf.Variable([[4, 5, 6], [7, 8, 9]])
A_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [16]:
b_tf = tf.Variable([[3], [1], [4]])
b_tf

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[3],
       [1],
       [4]], dtype=int32)>

### 2.  tampilkan ukuran matrix A dan vector b

In [12]:
A.shape

(2, 3)

In [17]:
b.shape

(3, 1)

### 3. kalikan matrix A dengan vector b

In [18]:
# numpy
np.dot(A, b)

array([[41],
       [65]])

In [19]:
# pytorch
torch.matmul(A_pt, b_pt)

tensor([[41],
        [65]])

In [21]:
# tensorflow
tf.matmul(A_tf, b_tf)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[41],
       [65]], dtype=int32)>

### 4. buat matrix B dengan ukuran 3x3

In [22]:
# numpy
B = np.array([[4, 5, 8], [3, 5, 9], [3, 2, 9]])
B

array([[4, 5, 8],
       [3, 5, 9],
       [3, 2, 9]])

In [23]:
# pytorch
B_pt = torch.tensor([[4, 5, 8], [3, 5, 9], [3, 2, 9]])
B_pt

tensor([[4, 5, 8],
        [3, 5, 9],
        [3, 2, 9]])

In [24]:
# tensorflow
B_tf = tf.Variable([[4, 5, 8], [3, 5, 9], [3, 2, 9]])
B_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[4, 5, 8],
       [3, 5, 9],
       [3, 2, 9]], dtype=int32)>

### 5. kalikan matrix A dengan matrix B


In [25]:
# numpy
np.dot(A, B)

array([[ 49,  57, 131],
       [ 79,  93, 209]])

In [26]:
# pytorch
torch.matmul(A_pt, B_pt)

tensor([[ 49,  57, 131],
        [ 79,  93, 209]])

In [28]:
# tensorflow
tf.matmul(A_tf, B_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 49,  57, 131],
       [ 79,  93, 209]], dtype=int32)>

### 6. buktikan apakah perkalian matrix bersifat komutatif? (AB=BA)?

In [29]:
AB = np.dot(A, B)
AB

array([[ 49,  57, 131],
       [ 79,  93, 209]])

In [30]:
BA = np.dot(B, A)
BA

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

disimpulkan bahwa perkalian matrix tidak bersifat komutatif