### 1. Buatlah matrix simstris ukuran 3x3 dan buktikan bahwa itu simetris

In [ ]:
import numpy as np

In [ ]:
# buatlah matriks simetris dengan ukuran 3x3
X_sym = np.array([[0, 1, 3], [1, 1, 3], [3, 3, 3]])
X_sym

array([[0, 1, 3],
       [1, 1, 3],
       [3, 3, 3]])

In [ ]:
X_sym.T

array([[0, 1, 3],
       [1, 1, 3],
       [3, 3, 3]])

In [ ]:
# buktikan bahwa itu merupakan matriks simetris
X_sym.T == X_sym

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### 2. Dengan pytorch, buatlah matrix identitas I dengan ukuran 4x4, buatlah vektor b_pt ukuran 4x1, lalu kalikan matix I dengan vektor b_pt

In [2]:
import torch

2.1 buatlah matrix identitas I ukuran 4x4

In [3]:
# matrix identitas I ukuran 4x4
I = torch.tensor([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
I

tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

2.2 buatlah vector b_pt ukuran 4x1

In [4]:
# vector b_pt ukuran 4x1
b_pt = torch.tensor([[0], [1], [2], [3]])
b_pt

tensor([[0],
        [1],
        [2],
        [3]])

2.3 kalikan matrix I dengan vector b_pt

In [5]:
# kalikan matrix I dengan vector b_pt
torch.matmul(I, b_pt)

tensor([[0],
        [1],
        [2],
        [3]])