### 1. buat matrix X dengan ukuran 2x3 lalu kalikan, jumlahkan, dan kurangkan dengan suatu skalar

1.1 Membuat matrix X dengan ukuran 2x3

In [2]:
import numpy as np

In [3]:
# buat matrix X dengan ukuran 2x3 dengan menggunakan numpy
X = np.array([[1, 2,3], [5, 6, 7]])
X

array([[1, 2, 3],
       [5, 6, 7]])

In [4]:
import torch

In [5]:
# buat matrix X_pt dengan ukuran 2x3 dengan menggunakan pytorch
X_pt = torch.tensor([[1, 4, 6], [5, 6, 7]])
X_pt

tensor([[1, 4, 6],
        [5, 6, 7]])

In [6]:
import tensorflow as tf

In [7]:
# buat matrix X dengan ukuran 2x3 dengan menggunakan tensorflow
X_tf = tf.Variable([[1, 3, 6], [8, 6, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 3, 6],
       [8, 6, 7]], dtype=int32)>

1.2 Mengalikan Matriks X dengan suatu skalar

In [8]:
# kalikan matriks X dengan suatu skalar
X * 6 # 6 adalah nilai scalar

array([[ 6, 12, 18],
       [30, 36, 42]])

In [9]:
# kalikan matriks X_pt dengan suatu skalar
torch.mul(X_pt, 4)

tensor([[ 4, 16, 24],
        [20, 24, 28]])

In [10]:
# kalikan matriks X_tf dengan suatu skalar
tf.multiply(X_tf, 3)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 3,  9, 18],
       [24, 18, 21]], dtype=int32)>

1.3 Menjumlahan matrix x dengan suatu skalar

In [11]:
# jumlahkan matriks X dengan suatu skalar
X + 2

array([[3, 4, 5],
       [7, 8, 9]])

In [12]:
# jumlahkan matriks X dengan suatu pytorch
torch.add(X_pt, 5)

tensor([[ 6,  9, 11],
        [10, 11, 12]])

In [13]:
# jumlahkan matriks X dengan suatu tensorflow
tf.add(X_tf, 7)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 8, 10, 13],
       [15, 13, 14]], dtype=int32)>

1.4 Mengurangkan matriks X dengan suatu matriks

In [14]:
# kurangkan matriks X dengan suatu skalar
X - 1

array([[0, 1, 2],
       [4, 5, 6]])

In [15]:
# kurangkan matriks X_pt dengan suatu skalar
torch.sub(X_pt, 4)

tensor([[-3,  0,  2],
        [ 1,  2,  3]])

In [16]:
# kurangkan matriks X_tf dengan suatu skalar
tf.subtract(X_tf, 8)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[-7, -5, -2],
       [ 0, -2, -1]], dtype=int32)>

### 2. Buat matrix Y dengan ukuran 2x3 lalu kalikan dengan matrix X

2.1 Buat matriks Y ukuran 2x3

In [17]:
# buat matrix Y dengan ukuran 2x3 dengan menggunakan numpy
Y = np.array([[1, 2, 3], [5, 6, 7]])
Y

array([[1, 2, 3],
       [5, 6, 7]])

In [18]:
# buat matrix Y_pt dengan ukuran 2x3 dengan menggunakan pytorch
Y_pt = torch.tensor([[9, 6, 4], [4, 3, 7]])
Y_pt

tensor([[9, 6, 4],
        [4, 3, 7]])

In [19]:
# buat matrix X_tf dengan ukuran 2x3 dengan menggunakan tensorflow
Y_tf = tf.Variable([[1, 3, 6], [8, 6, 7]])
Y_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 3, 6],
       [8, 6, 7]], dtype=int32)>

2.2 Kalikan matrix X dengan Y

In [20]:
# kalikan matriks X dan Y
X * Y

array([[ 1,  4,  9],
       [25, 36, 49]])

In [22]:
# kalikan matriks X_pt dan Y_pt
torch.mul(X_pt, Y_pt)

tensor([[ 9, 24, 24],
        [20, 18, 49]])

In [23]:
# kalikan matriks X_tf dan Y_tf
tf.multiply(X_tf, Y_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  9, 36],
       [64, 36, 49]], dtype=int32)>