1. Buat matrix x dengan ukuran 2x3

In [ ]:
import numpy as np

In [ ]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([[2, 3, 4], [1, 2, 3]])
X

array([[2, 3, 4],
       [1, 2, 3]])

In [ ]:
import torch

In [ ]:
# buat matrix X dengan ukuran 2x3 menggunakan pytorch
X_pt = torch.tensor([[2, 3, 4], [1, 2, 3]])
X_pt

tensor([[2, 3, 4],
        [1, 2, 3]])

In [ ]:
import tensorflow as tf

In [ ]:
# buat matrix X dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[2, 3, 4], [1, 2, 3]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[2, 3, 4],
       [1, 2, 3]], dtype=int32)>

2. Melakukan transpose pada semua matrix di atas

In [ ]:
# melakukan transpose pada matrix X
X_t = X.T
X_t

array([[2, 1],
       [3, 2],
       [4, 3]])

In [ ]:
# melakukan transpose pada matrix X_pt
X_pt_t = X.T
X_pt_t

array([[2, 1],
       [3, 2],
       [4, 3]])

In [ ]:
# melakukan transpose pada matrix X_tf
X_tf_t = X.T
X_tf_t

array([[2, 1],
       [3, 2],
       [4, 3]])