### 1. Membuat matriks X ukuran 2x3, lalu jumlahkan semua elemen matrix menggunakan fungsi sum

1.1 membuat matriks X menggunakan numpy

In [ ]:
import numpy as np

# Membuat matriks 2x3
X = np.array([[1, 2, 3],
              [4, 5, 6]])

print(X)
print(f"Ukuran matriks: {X.shape}")

[[1 2 3]
 [4 5 6]]
Ukuran matriks: (2, 3)


1.2 menjumlahkan semua elemen matriks menggunakan fungsi sum

In [ ]:
import numpy as np

X = np.array([[1, 2, 3],
              [4, 5, 6]])

# Menjumlahkan SEMUA elemen dalam matriks
total_sum = np.sum(X)

print(f"Matriks X")
print(f"Hasil penjumlahan semua elemen: {total_sum}")

Matriks X
Hasil penjumlahan semua elemen: 21


1.3 membuat matriks X ukuran 2x3 dengan menggunakan tensorflow

In [ ]:
import tensorflow as tf

# Membuat matriks 2x3
X_tf = tf.constant([[1, 2, 3],
                    [4, 5, 6]])

print("Matriks X_tf:")
print(X_tf)
print(f"Ukuran (Shape): {X_tf.shape}")

Matriks X_tf:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Ukuran (Shape): (2, 3)


### 2. Hitung hasil penjumlahan seluruh elemen matriks X

In [1]:
# hasil penjumlahan seluruh elemen matriks X
import numpy as np

X = np.array([[1, 2, 3],
              [4, 5, 6]])

# Menjumlahkan SEMUA elemen dalam matriks
total_sum = np.sum(X)

print(f"Matriks X")
print(f"Hasil penjumlahan semua elemen: {total_sum}")

Matriks X
Hasil penjumlahan semua elemen: 21


In [2]:
# hasil penjumlahan seluruh elemen matriks X_pt
import torch

# Membuat matriks 2x3 di PyTorch
X_pt = torch.tensor([[1, 2, 3],
                     [4, 5, 6]])

# Menghitung hasil penjumlahan seluruh elemen
total_sum_pt = torch.sum(X_pt)

print(f"Matriks X_pt:\n{X_pt}")
print(f"Hasil penjumlahan seluruh elemen (PyTorch): {total_sum_pt.item()}")

Matriks X_pt:
tensor([[1, 2, 3],
        [4, 5, 6]])
Hasil penjumlahan seluruh elemen (PyTorch): 21


In [3]:
# hasil penjumlahan seluruh elemen matriks X_tf
import tensorflow as tf

X_tf = tf.constant([[1, 2, 3],
                    [4, 5, 6]])

# Menghitung total penjumlahan
total_sum_tf = tf.reduce_sum(X_tf)

print(f"Hasil penjumlahan seluruh elemen (TF): {total_sum_tf.numpy()}")

Hasil penjumlahan seluruh elemen (TF): 21


### 3. Hitung hasil penjumlahan matrix X berdasarkan row nya

In [4]:
# matrix X
import numpy as np
X = np.array([[1, 2, 3],
              [4, 5, 6]])

row_sum_np = np.sum(X, axis=1)
print(f"Hasil per baris (NumPy): {row_sum_np}")

Hasil per baris (NumPy): [ 6 15]


In [5]:
# matriks X_pt
import torch

# Membuat matriks 2x3
X_pt = torch.tensor([[1, 2, 3],
                     [4, 5, 6]])

# Menghitung hasil penjumlahan berdasarkan baris (row)
row_sum = torch.sum(X_pt, dim=1)

print(f"Matriks X_pt:\n{X_pt}")
print(f"Hasil penjumlahan per baris: {row_sum}")

Matriks X_pt:
tensor([[1, 2, 3],
        [4, 5, 6]])
Hasil penjumlahan per baris: tensor([ 6, 15])


In [7]:
# matrix X_tf
import tensorflow as tf

# matriks X_tf (2x3)
X_tf = tf.Variable([[1, 2, 3],
                    [4, 5, 6]])

# Menghitung penjumlahan berdasarkan baris
row_sum_tf = tf.reduce_sum(X_tf, axis=1)

print("Matriks X_tf:")
print(X_tf.numpy())
print(f"\nHasil penjumlahan per baris: {row_sum_tf.numpy()}")
# Output: [ 6 15]

Matriks X_tf:
[[1 2 3]
 [4 5 6]]

Hasil penjumlahan per baris: [ 6 15]


### 4. hitung hasil penjumlahan matrix X berdasarkan kolomnya

In [8]:
# matrix X
import numpy as np
X = np.array([[1, 2, 3],
              [4, 5, 6]])

col_sum_np = np.sum(X, axis=0)
print(f"Hasil per kolom (NumPy): {col_sum_np}")

Hasil per kolom (NumPy): [5 7 9]


In [10]:
# matrix X_pt
import torch
X_pt = torch.tensor([[1, 2, 3],
                     [4, 5, 6]])

col_sum_pt = torch.sum(X_pt, dim=0)
print(f"Hasil per kolom (PyTorch): {col_sum_pt}")

Hasil per kolom (PyTorch): tensor([5, 7, 9])


In [9]:
# matrix X_tf
import tensorflow as tf
X_tf = tf.constant([[1, 2, 3],
                    [4, 5, 6]])

col_sum_tf = tf.reduce_sum(X_tf, axis=0)
print(f"Hasil per kolom (TF): {col_sum_tf.numpy()}")

Hasil per kolom (TF): [5 7 9]


### 5. Hitung hasil nilai yang dicari dari matrix X

5.1 nilai minimal

In [11]:
# nilai minimal dari matrix X
import numpy as np
X = np.array([[1, 2, 3],
              [4, 5, 6]])

min_val = np.min(X)
# Atau: min_val = X.min()

print(f"Nilai minimal (NumPy): {min_val}")

Nilai minimal (NumPy): 1


In [12]:
# nilai minimal dari matrix X_pt
import torch
X_pt = torch.tensor([[1, 2, 3],
                     [4, 5, 6]])

min_val_pt = torch.min(X_pt)

print(f"Nilai minimal (PyTorch): {min_val_pt.item()}")

Nilai minimal (PyTorch): 1


In [13]:
# nilai minimal dari matrix X_tf
import tensorflow as tf
X_tf = tf.Variable([[1, 2, 3],
                    [4, 5, 6]])

min_val_tf = tf.reduce_min(X_tf)

print(f"Nilai minimal (TF): {min_val_tf.numpy()}")

Nilai minimal (TF): 1


5.2 nilai maksimal

In [14]:
# nilai maksimal dari matriks X
import numpy as np
X = np.array([[1, 2, 3],
              [4, 5, 6]])

max_val = np.max(X)
print(f"Nilai maksimal (NumPy): {max_val}")

Nilai maksimal (NumPy): 6


In [15]:
# nilai maksimal dari matrix X_pt
import torch
X_pt = torch.tensor([[1, 2, 3],
                     [4, 8, 6]])

max_val_pt = torch.max(X_pt)
print(f"Nilai maksimal (PyTorch): {max_val_pt.item()}")

Nilai maksimal (PyTorch): 8


In [17]:
# nilai maksimal dari matrix X_tf
import tensorflow as tf
X_tf = tf.Variable([[1, 9, 3],
                    [4, 5, 6]])

max_val_tf = tf.reduce_max(X_tf)
print(f"Nilai maksimal (TF): {max_val_tf.numpy()}")

Nilai maksimal (TF): 9


5.3 nilai rata-rata

In [18]:
# nilai rata - rata dari matrix X
import numpy as np
X = np.array([[1, 2, 3],
              [4, 5, 6]])

mean_val = np.mean(X)
print(f"Nilai rata-rata (NumPy): {mean_val}")

Nilai rata-rata (NumPy): 3.5


In [22]:
# nilai rata - rata dari matrix X_pt
import torch
X_pt = torch.tensor([[1, 2, 3],
                     [4, 5, 6]], dtype = torch.float32)

mean_val_pt = torch.mean(X_pt)
print(f"Nilai rata-rata (PyTorch): {mean_val_pt}")

Nilai rata-rata (PyTorch): 3.5


In [24]:
# nilai rata - rata dari matrix X_tf
import tensorflow as tf
X_tf = tf.Variable([[1, 2, 3],
                    [4, 8, 6]])

mean_val_tf = tf.reduce_mean(X_tf)
print(f"Nilai rata-rata (TF): {mean_val_tf}")

Nilai rata-rata (TF): 4


### 6. Hitung hasil perkalian seluruh elemen matrix X

In [25]:
# hasil perkalian seluruh elemen matrix X
import numpy as np
X = np.array([[1, 2, 3],
              [4, 5, 6]])

total_prod = np.prod(X)
print(f"Hasil perkalian (NumPy): {total_prod}")

Hasil perkalian (NumPy): 720


In [28]:
# hasil perkalian seluruh elemen matrix X_pt
import torch
X_pt = torch.tensor([[1, 2, 3],
                     [4, 5, 6]])

total_prod_pt = torch.prod(X_pt)
print(f"Hasil perkalian (PyTorch): {total_prod_pt}")

Hasil perkalian (PyTorch): 720


In [29]:
# hasil perkalian seluruh elemen matrix X_tf
import tensorflow as tf
X_tf = tf.Variable([[1, 2, 3],
                    [4, 5, 6]])

total_prod_tf = tf.reduce_prod(X_tf)
print(f"Hasil perkalian (TF): {total_prod_tf}")

Hasil perkalian (TF): 720
