1. buat vector x dan y dengan ukuran 1x3

In [ ]:
import numpy as np

In [ ]:
# buat vector x dan y dengan ukuran 1x3 menggunakan numpy
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [ ]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [ ]:
import torch

In [ ]:
# buat vector x_pt dan y_pt dengan ukuran 1x3 menggunakan pytorch
x_pt = torch.tensor([3, 4, 5])
x_pt

tensor([3, 4, 5])

In [ ]:
y_pt = torch.tensor([6, 7, 8])
y_pt

tensor([6, 7, 8])

In [ ]:
import tensorflow as tf

In [ ]:
# buat vector x_tf dan y_tf dengan ukuran 1x3 menggunakan tensorflow
x_tf = tf.Variable([7, 8, 9])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([7, 8, 9], dtype=int32)>

In [ ]:
y_tf = tf.Variable([10, 11, 12])
y_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([10, 11, 12], dtype=int32)>

2. hitung perkalian dot product antara vector x dan vector y

In [ ]:
# menghitung perkalian dot product menggunakan numpy
np.dot(x,y)

np.int64(32)

In [ ]:
# menghitung perkalian dot product menggunakan pytorch
torch.dot(x_pt, y_pt)

tensor(86)

In [ ]:
# menghitung perkalian dot product menggunakan tensorflow
tf.reduce_sum(tf.multiply(x_tf, y_tf))

<tf.Tensor: shape=(), dtype=int32, numpy=266>

3. lakukan perhitungan exercise menggunakan collab

In [ ]:
# 3.1 what is Y.T, Y = ([[42, 4, 7, 99], [-99, -3, 17, 22]]
Y = np.array ([[42, 4, 7, 99], [-99, -3, 17, 22]])
Y

array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]])

In [ ]:
Y_t = Y.T
Y_t

array([[ 42, -99],
       [  4,  -3],
       [  7,  17],
       [ 99,  22]])

In [24]:
# 3.2 what is the hadamart product of these matrices
# A = ([[25, 10], [-2, 1]]) * B = ([[-1, 7], [10, 8]])
A = np.array([[25, 10], [-2, 1]])
B = np.array([[-1, 7], [10, 8]])

(A * B)

array([[-25,  70],
       [-20,   8]])

In [25]:
# what is the dot product of the tensor w and x?
# w = ([-1, 2, 2])
# x = ([5, 10, 0])
w = np.array([-1, 2, 2])
x = np.array([5, 10, 0])

np.dot(w, x)

np.int64(15)